[package]
name = "axelar-gateway"
version = "0.1.0"
authors = ["jack <jackson.virgo1@gmail.com>"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = ["cranelift"]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]
cranelift = ["cosmwasm-vm/default-cranelift"]
singlepass = ["cosmwasm-vm/default-singlepass"]

[dependencies]
sha3 = "0.9"
k256 = { version = "0.7.2", features = ["ecdsa", "sha256"] }
axelar-gateway-contracts = { path = "../../packages/axelar-gateway-contracts", default-features = false, version = "0.1.0"}
cosmwasm-crypto = "0.14.0-beta1"
cosmwasm-std = { version = "0.10.1" }
cosmwasm-storage = { version = "0.10.1" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

[dev-dependencies]
cosmwasm-vm = { version = "0.10.1", default-features = false }
axelar-crypto = { path = "../crypto", default-features = false, version = "0.1.0"}
rand_core = { version = "0.5", features = ["getrandom"] }
cosmwasm-schema = { version = "0.10.1" }
