[package]
name = "axelar-gateway"
version = "0.1.0"
authors = ["Axelar Network"]
edition = "2018"
description = ""
license = "Apache-2.0"
repository = ""
homepage = ""
documentation = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.2"
cosmwasm-std = { version = "0.10.1", default-features = false, features = ["iterator"] }
cosmwasm-storage = { version = "0.10.1", default-features = false, features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
